ASSET_DIR=assets
COMPONENT_DIR=components
IN_CSS=$(ASSET_DIR)/input.css
OUT_CSS=$(ASSET_DIR)/main.css

all: css templates run 

css:
	tailwindcss -i $(IN_CSS) -o $(OUT_CSS) -m
	echo "/* Generated by tailwindcss */" >> $(OUT_CSS)

templates: 
	templ generate $(COMPONENT_DIR)

run:
	go run *.go

.Phony: clean
clean: 
	[ -f $(OUT_CSS) ] && rm $(OUT_CSS) || true
	[ -d $(COMPONENT_DIR) ] && rm $(COMPONENT_DIR)/*_templ.go || true

