ASSET_DIR=assets
COMPONENT_DIR=components
IN_CSS=$(ASSET_DIR)/input.css
OUT_CSS=$(ASSET_DIR)/main.css
PROXY="http://localhost:8080"
BINARY_NAME=masonictempl
WORKDIR ?= $(shell pwd)

# This can be passed at the command line when running make
# like so: `BIN_DIR=/your/path/here make`
# If this value is not specified it will default to your GOBIN
# setting, and if that is empty it will default to a local `bin/`
# directory.
BIN_DIR ?= $(shell go env GOPRIVATE)

ifeq ($(BIN_DIR),) 
	BIN_DIR = bin
endif

PORT ?= $(or $(shell echo $$PORT),8080)


all: css templates run 

css:
	tailwindcss -i $(IN_CSS) -o $(OUT_CSS) -m
	echo "/* Generated by tailwindcss */" >> $(OUT_CSS)

templates: 
	templ generate $(COMPONENT_DIR)

run: build
	./$(BIN_DIR)/$(BINARY_NAME) --port $(PORT) --workdir $(WORKDIR)


.PHONY: clean
clean: 
	[ -f $(OUT_CSS) ] && rm $(OUT_CSS) || true
	[ -d $(COMPONENT_DIR) ] && rm $(COMPONENT_DIR)/*_templ.go || true


.PHONY: hot-reload
hot-reload:
	templ generate --watch --proxy="http://localhost:8080" --cmd="make runserver"

.PHONY: runserver
runserver:
	go run . --port $(PORT) --workdir $(WORKDIR)

.PHONY: kill
kill:
		-kill $(shell jobs -p 2>/dev/null) || true

# Build will create the BIN_DIR first if it does not exist
# Then create a binary inside of the destination.
# IMPORTANT: Could potentially require root or admin privileges
# depending on the path. It's best to install somewhere
# with user permissions.
.PHONY: build
build:
	mkdir -p $(BIN_DIR) && go build -o $(BIN_DIR)/$(BINARY_NAME)

