// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"time"
)

//go:embed footerLinks.json
var footerData []byte

type FooterLink struct {
	Url  string `json:"url"`
	Text string `json:"text"`
	Icon string `json:"icon"`
}

func FooterLinksFromData(data []byte) []FooterLink {
	var links []FooterLink
	if err := json.Unmarshal(data, &links); err != nil {
		panic(err)
	}
	return links
}

func WithDefaultLinks() []FooterLink {
	return FooterLinksFromData(footerData)
}

func getYear() string {
	return fmt.Sprintf("%d", time.Now().Year())
}

func Footer(links ...FooterLink) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<footer class=\"rounded-lg shadow m-4\"><div class=\"w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between\"><span class=\"text-sm text-gray-500 sm:text-center dark:text-gray-400\">© ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(getYear())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/footer.templ`, Line: 38, Col: 90}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" <a href=\"\" class=\"hover:underline\">Mason Tucker</a>. All Rights Reserved.</span><!-- <ul class=\"flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 dark:text-gray-400 sm:mt-0\">\n        <li>\n            <a href=\"#\" class=\"hover:underline me-4 md:me-6\">About</a>\n        </li>\n        <li>\n            <a href=\"#\" class=\"hover:underline me-4 md:me-6\">Privacy Policy</a>\n        </li>\n        <li>\n            <a href=\"#\" class=\"hover:underline me-4 md:me-6\">Licensing</a>\n        </li>\n        <li>\n            <a href=\"#\" class=\"hover:underline\">Contact</a>\n        </li>\n    </ul> --></div></footer><!-- <ul class=\"flex flex-wrap items-center justify-center mt-4\">\n    for _, link := range links {\n      <li class=\"mr-6\">\n        <a \n          class=\"text-link-blue hover:underline underline-offset-4 hover:font-bold\"\n          href={templ.SafeURL(link.Url)}\n          target=\"\"\n        >\n          { link.Text }\n        </a>\n      </li>\n    }\n  </ul> -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
