// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func LoadMarkdown(id string, content string) templ.ComponentScript {
	return templ.ComponentScript{
		Name:       `__templ_LoadMarkdown_10fb`,
		Function:   `function __templ_LoadMarkdown_10fb(id, content){document.getElementById(id).innerHTML = marked.parse(content);}`,
		Call:       templ.SafeScript(`__templ_LoadMarkdown_10fb`, id, content),
		CallInline: templ.SafeScriptInline(`__templ_LoadMarkdown_10fb`, id, content),
	}
}
